name: uaepass
description: UAE PASS service allows using a mobile device as a secure form of identification. UAE PASS automates and simplifies managing digital identity in mobile devices for users.
version: 0.0.5
repository: https://github.com/Alkhajeh/Flutter-UAEPass
issue_tracker: https://github.com/Alkhajeh/Flutter-UAEPass/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  url_launcher: ^6.2.6
  flutter_inappwebview: ^6.0.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.uaepass
        pluginClass: UaepassPlugin
      ios:
        pluginClass: UaepassPlugin

  assets:
    - images/
